import fs from 'fs';
let code = fs.readFileSync('src/utils/firebaseErrors.ts', 'utf8');
code = code.replace("import { auth } from '../firebase';", "");
code = code.replace(/userId: auth\.currentUser\?.uid,/g, "userId: 'supabase-user',");
code = code.replace(/email: auth\.currentUser\?.email,/g, "email: 'unknown',");
code = code.replace(/emailVerified: auth\.currentUser\?.emailVerified,/g, "emailVerified: false,");
code = code.replace(/isAnonymous: auth\.currentUser\?.isAnonymous,/g, "isAnonymous: false,");
code = code.replace(/tenantId: auth\.currentUser\?.tenantId,/g, "tenantId: null,");
code = code.replace(/providerInfo: auth\.currentUser\?.providerData.*\|\| \[\]/g, "providerInfo: []");
fs.writeFileSync('src/utils/firebaseErrors.ts', code);
console.log("Patched errors");
